### ISSUE TITLE
Editor doesn't build or output an error message when a filename contains some special characters

### ISSUE THREAD

**Issue by petercowal** [gracelang/grace-web-editor#18]
Trying to build a file with `'` in the name fails; browser console shows "unexpected string"

Adding a `"` to a filename renders the file inaccessible.

**Comment by Dmitri-2** [comment]
Pushed fix (from master branch), as commit #01e6ded. It now uses a reg-ex to check for invalid characters.

**Comment by apblack** [comment]
This should actually work, although making it work is a low priority, I think.  The file-name strings are escaped to turn them into valid JS identifiers;
the escaping is probably missing some cases.
