### ISSUE TITLE
Editing is broken after loading a file with the same name as a built-in module

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#19]
If one loads a one of the minigrace source files into the web editor (I tried objectdraw.grace and minitest.grace), attempts to edit introduce garbage.  The first inserted keystroke seems to work, but leaves the cursor in the wrong place, the second introduces the last two character typed, and so on, getting progressively worse.

After deleting the file from the editor's list of files, things slowly go back to normal!

This was originally submitted as [minigrace issue #163](https://github.com/gracelang/minigrace/issues/163)

**Comment by Dmitri-2** [comment]
I'll try to take a look at this today to see what's going on. The fix shouldn't be overly complicated...

**Comment by apblack** [comment]
Great!  You now know more about the Web editor and its file list structure than anyone else on the planet.

**Comment by Dmitri-2** [comment]
Fixed with commits 47a1754 and 39193d0.
