### ISSUE TITLE
Can't rename a directory

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#21]
Files can be renamed in the title bar of the editing pane, but there seems to be no way to rename a directory.

**Comment by Dmitri-2** [comment]
I think this is something that I'll add to the right-click menu (context menu) as a second option.

**Comment by apblack** [comment]
> I think this is something that I'll add to the right-click menu (context menu) as a second option.

Sounds like a very good approach.

**Comment by Dmitri-2** [comment]
Fix in-progress — basic renaming capability added in commit 6393978. The next version of renaming functionality will use a non-ui function to do the renaming.
