### ISSUE TITLE
"Search" does not toggle to "Replace"

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#22]
If one opens the search dialog by clicking "Search", the word "Search" changes to "Replace", and a second click opens the Replace dialog.  

However, if one opens the search dialog with Cmd-F, the word "Search" does not change, and there is no apparent way to open the "Replace" dialog.  (Cmd-Opt-F works on the Mac, but not on Windows).

**Comment by Dmitri-2** [comment]
This is fixed in commit 972e4e8. Also, a nice shortcut for replace is pressing Cmd-F twice. In fact, each Cmd-F press continues to toggle between the "find" and "find and replace" states.
