### ISSUE TITLE
No version number

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#23]
The web editor displays the version number of the _compiler_ that it contains (in the settings pane).

However, it does not display the versions number of the editor itself.  This is going to make it hard to track bugs.

**Comment by apblack** [comment]
The version number should be a sequential number (for easy memorization) as well as a short github commit id.  Here are ways of getting these:

$ git log --oneline | wc -l
     107
$ git log -n1 --abbrev --oneline
0eebc8a Adds icons.

In both cases, piping through `| awk '{ print $1; }` will grab the field that you want without spaces.

**Comment by Dmitri-2** [comment]
Resolved in commit babbf77. Added IDE version number, last git commit, and the date the web editor was last built to the settings pane in the web editor. (Accompanying "calcVersion" script also pushed to minigrace repo).
