### ISSUE TITLE
Syntax highlighter doesn't understand "\\"

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#35]
A string like `("\\")` is not highlighted correctly.  The highlighter sees the \\", and thinks that the closing quote is a escaped, whereas in fact it's not.

**Comment by kjx** [comment]
I don't think that is a string. How can you tell?

kernan says:

>>> print "\"                                                               
source code:1: L0006: Unterminated string literal: expected '"'

**Comment by apblack** [comment]
`"\"` is not a string; it's not terminated.  `"\\"` is a string; it has length and contains just the backslash character.  _Minigrace_ accepts it happily; I've no doubt that _kernan_ does too. 

This issue is about the syntax-highlighting in grace-mode in ACE.

**Comment by apblack** [comment]
This is fixed in commit 6c412310
