### ISSUE TITLE
Feature request: download all files as zip archive

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#36]
Students collect a lot of files over the course of a quarter.  They ask to be able to download them as a zip archive.    Or, at least, to select multiple files and download those.

**Comment by Dmitri-2** [comment]
This has been added in commit 86dc412. I have added a button for this in the Refactor menu, however, there might be a better place for it. Additionally, I also plan to expand this to allow individual folders to be downloaded (the code is there, but the UI elements need to be linked to it).

**Comment by apblack** [comment]
Wow, this is impressive!  

I was thinking about where in the UI we should put this functionality.

**Comment by Dmitri-2** [comment]
Refactor menu renamed to "Utilities" with commit 8bfdade.
