### ISSUE TITLE
Too many alerts

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#39]
If one tries to upload a module with a name that is already taken, one gets __three__ alerts.  The first is unnecessary: there is no action to be taken other than clicking "OK".  The second asks if the user wants to rename the file; if she says yes, then a third alert asks for the new name.

In spite of this, _none_ of these alerts tells the user what the existing (taken) name is. If she is uploading multiple files at once, there is no way to know which name is causing problems.

It seems to me that there should be exactly _one_ alert, which can tell the user what has happened (including the file name) and offer the choice of renaming the file or abandoning the upload.   Can it be one of the better-looking JavaScript alerts?

**Comment by Dmitri-2** [comment]
Fixed in commit 8fccbe7. The original design called for the built-in alerts, since they are the only way to truly interrupt execution and wait for user input. This has now been re-written to use the JavaScript alerts and use call-backs to manage the asynchronous aspects of the code.
