### ISSUE TITLE
Syntax error makers remain after buffer switch

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#43]
On a syntax error, the offending range is highlighted in orange.  This is accomplished by a call to
```
clearMarkers(session)
```
when a change is detected in the buffer (see line 254 of editor.js).

However, if the user switches edit buffer, the marker is not cleared: a range in a completely different file is highlighted.

The markers should be turned off when the user switches buffer.

**Comment by Dmitri-2** [comment]
Fixed in commit a6f0cf4. This was a really easy fix to make!
