### ISSUE TITLE
Add link to documentation website at top of editor

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#46]
In the row of icons at the top of the editor, it would be nice to have a question-mark icon that opens the documentation website in another window.

**Comment by Dmitri-2** [comment]
Added a "Help" button with commit: c949546
Do we want this button to simply be a question mark "?" or actually be an question mark icon? (Like we used for the add file/directory buttons).

**Comment by Dmitri-2** [comment]
Completed with commit c052d14d622fadf12c2d5d419e73bf158d485447.
