### ISSUE TITLE
Rename of file on upload

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#47]
If one tries to upload into the IDE a file that has the same name as one of the built-in modules, the IDE warns you that this might be a bad idea.  But it does _not_ give you the option of renaming the file on upload (which is what it does if you try an upload a file that has the same name as one already present.)

Could the user be offered the option of doing a rename?

**Comment by Dmitri-2** [comment]
Fixed in d6380bfe43d39bf2df003a18af8c2f83df06d48f.
