### ISSUE TITLE
Files go missing

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#48]
A student using Mozilla experienced this in class.  He claimed that the whole contents of his "Homework file" directory had gone missing.

Refreshing the browser didn't bring it back.

So I opened Firebug and looked.  The files were present in localStorage.  I was able to grab the contents in Firebug and paste it back into new editor panes.

The directory that the files were in was also present, with value "open".

The student doesn't know how the files got into this state — I've asked him, if it happens again, to try and remember what he had done.  I'm guessing that some renaming was involved. 

What puzzles me is this. The file tree is presumably re-created from localStorage when the browser is first opened, and when it is refreshed.   How can the files be present in localStorage but not appear in the file tree?

Maybe we need a "validate" method that checks localStorage for inconsistencies, and rebuilds or fixes it?

**Comment by Dmitri-2** [comment]
When did this occur? I will investigate it and try to see if I can replicate it. 
I'll also see if I can find anything that Mozilla does differently that could cause this error. 

I am not sure how this could happen... The code that loads files and directories is very straightforward: if there is a "file:" prefix, it is loaded as a file, if there is a "directory:" prefix, it is loaded as a directory. 

We could definitely add a "validate" function that checks for errors, and restores files and directories. Though, I have never seen file/directory identifiers in localStorage be corrupted through normal use, so I'm hoping this is a isolated problem.

**Comment by apblack** [comment]
It happened in class today.  The best I could get from Firebug is a partial printout of localStrorage:

`Storage { file-data:Practice Folder/Week 02/Week 02 - 2 .grace: "{"cursorRow":6,"cursorCol":20,"scro…", directory:Practice Folder/Week 02: "open", file-data:Practice Folder/TURN TAKING.grace: "{"cursorRow":11,"cursorCol":0,"scro…", directory:Recovered: "open", file:Recovered/polygons.grace: "dialect "logo" method square (side…", file-data:Practice File: Circles: "{"folds":[]}", file:Practice Folder/In Class Practice.grace: "def b = 4 def c = 7 def n = (b^2) -…", file-data:HW2.grace: "{"folds":[]}", editorFoldStyle: "markbegin", file-data:Practice Folder/Number Line Plot: "{"cursorRow":31,"cursorCol":12,"scr…", 75 more… }`

Unfortunately, the `file:..` components are not shown here.

**Comment by Dmitri-2** [comment]
I looked at this and I have both files and directories disappearing in Mozilla Firefox (from what I can tell, primarily due to renaming directories and possibly files). 
#### **I would highly recommend students NOT to use Firefox for running the IDE.** 
It would be best if they could download Chrome, as that is the browser for which we can guarantee that there won't be any errors so major that they can't be fixed by a page refresh. 

If they must use Firefox, then they should be very careful about renaming, especially for directories.

**Comment by apblack** [comment]
Fixed in c2195f17
