### ISSUE TITLE
Needs "Insert Unicode" utility

### ISSUE THREAD

**Issue by apblack** [gracelang/grace-web-editor#59]
There is a replace Unicode Utility on the Utilities tab, which replaces the six Unicode characters that have [ASCII di-graph equivalents](http://web.cecs.pdx.edu/~grace/doc/lang-spec/#character-equivalencies) by those ASCII equivalents.

It would be useful to have the inverse utility: replace di-graphs by Unicode.  Or, perhaps the single button should be a toggle.

It's tricky to come up with accurate and concise names for the two operations.

**Comment by apblack** [comment]
Perhaps the buttons could be something like `⟦`  ⤻  `[[` and `[[` ⤻ `⟦` ?
Of course, the buttons would perform all six replacements,  but the pictographs show the general idea.

**Comment by KimBruce** [comment]
Works for me, probably better than ASCII -> Unicode and reverse as novices likely don't know what ASCII or Unicode is.

**Comment by kjx** [comment]
Although I'm unlikely to convince anyone, the underlying problem is the existence of the digraphs.

How does having to have these buttons help novices?

**Comment by apblack** [comment]
> Although I'm unlikely to convince anyone, the underlying problem is the existence of the digraphs.

Quite right!  Let's go back to ICL 1900-series 6-bit bytes.  They were good enough for us, so why not for today's learners?

Oops, sorry, wrong issue tracker.  That's a language design issue.

**Comment by apblack** [comment]
This is implemented in #4657b4b; the icons are improved (I hope) in #be810e9.
